# Generated by Django 2.2.2 on 2020-06-24 22:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATEFP', models.CharField(max_length=2)),
                ('PLACEFP', models.CharField(max_length=5)),
                ('PLACENS', models.CharField(max_length=8)),
                ('GEOID', models.CharField(max_length=7)),
                ('NAME', models.CharField(max_length=100)),
                ('NAMELSAD', models.CharField(max_length=100)),
                ('LSAD', models.CharField(max_length=2)),
                ('CLASSFP', models.CharField(max_length=2)),
                ('PCICBSA', models.CharField(max_length=1)),
                ('PCINECTA', models.CharField(max_length=1)),
                ('MTFCC', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.BigIntegerField()),
                ('AWATER', models.BigIntegerField()),
                ('INTPTLAT', models.CharField(max_length=11)),
                ('INTPTLON', models.CharField(max_length=12)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATEFP', models.CharField(max_length=2)),
                ('COUNTYFP', models.CharField(max_length=3)),
                ('COUNTYNS', models.CharField(max_length=8)),
                ('GEOID', models.CharField(max_length=5)),
                ('NAME', models.CharField(max_length=100)),
                ('NAMELSAD', models.CharField(max_length=100)),
                ('LSAD', models.CharField(max_length=2)),
                ('CLASSFP', models.CharField(max_length=2)),
                ('MTFCC', models.CharField(max_length=5)),
                ('CSAFP', models.CharField(max_length=3)),
                ('CBSAFP', models.CharField(max_length=5)),
                ('METDIVFP', models.CharField(max_length=5)),
                ('FUNCSTAT', models.CharField(max_length=1)),
                ('ALAND', models.BigIntegerField()),
                ('AWATER', models.BigIntegerField()),
                ('INTPTLAT', models.CharField(max_length=11)),
                ('INTPTLON', models.CharField(max_length=12)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
